name: Link Check
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --no-progress
            --retry-wait 2
            --max-retries 2
            --accept 200,206
            --config lychee.toml
            "**/*.html" "**/*.md"

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
